App styles
BoilerMake/frontend pull request #24
Opened 2017-07-27 00:38 UTC by colejoh

2017-07-27 02:34 UTC, nickysemenza requested changes
Looks 🔥  overall, just a few misc comments / thoughts.

Might be good to fix the UI bug on the interest signup box so that this can get merged in to master

2017-07-27 02:34 UTC, nickysemenza commented on src/assets/_vars.scss
> -$font-body: 'Avenir Next', sans-serif;
if we're done with Avenir Next, you can go ahead and kill it from `src/fonts/`

2017-07-27 02:34 UTC, nickysemenza commented on src/index.js
> -  document.getElementById('root')
why this?

2017-07-27 02:34 UTC, nickysemenza commented on src/assets/index.scss
> +.max-width {
imo it's kind of confusing to have a custom class name that's the same as a standard property name- perhaps name it something that describes it's purpose, `fullWidthContainer` or something along those lines maybe?

2017-07-27 02:34 UTC, nickysemenza commented on src/pages/Application/ApplicationForm.js
> +                        {/* <Select ref="schoolSelect"
i know it's commented out right now, but this should end up in it's own component, even though it isn't reusable, it's cleaner and keeps redux logic outside of `<ApplicationForm/>`

2017-07-27 13:08 UTC, kedarv requested changes
Mostly nitpicky fixes on my part, take a look at review from @nickysemenza and feel free to merge

2017-07-27 13:08 UTC, kedarv commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,700" rel="stylesheet">
Are we using all of these weights?

2017-07-27 13:08 UTC, kedarv commented on src/assets/_application.scss
> +.paddingr {
nitpick: I don't like these names for padding and margin modifiers

2017-07-27 13:08 UTC, kedarv commented on src/assets/_application.scss
> +.Select-control {
lowercase `s`

2017-07-27 13:15 UTC, colejoh commented on src/assets/_application.scss
> +.Select-control {
This is a component that we import (react select) I don't have control over the class names, just trying to overwrite the styling.

2017-07-27 13:16 UTC, colejoh commented on src/assets/_application.scss
> +.paddingr {
We need to define a standard. What do you prefer?

2017-07-27 13:17 UTC, colejoh commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,700" rel="stylesheet">
Likely not. I was going to take out either the 500 or the 700 when I figured out which one looked better.

2017-07-27 13:17 UTC, colejoh commented on src/pages/Application/ApplicationForm.js
> +                        {/* <Select ref="schoolSelect"
There's a lot of refactoring that needs to be done.

2017-07-27 13:18 UTC, colejoh commented on src/assets/index.scss
> +.max-width {
I don't think it's bad. I've seen it done elsewhere.

2017-07-27 13:18 UTC, colejoh commented on src/assets/_vars.scss
> -$font-body: 'Avenir Next', sans-serif;
Will do

2017-07-27 18:12 UTC, nickysemenza commented on src/assets/_application.scss
> +.Select-control {
fyi - https://github.com/JedWatson/react-select#custom-classnames

2017-07-27 18:14 UTC, nickysemenza commented on src/assets/_application.scss
> +.paddingr {
we should have a discussion on slack probably, IMO some variation of [BEM](https://css-tricks.com/bem-101/) usually works well, but open to other suggestions

2017-07-28 03:22 UTC, nickysemenza commented on src/assets/_application.scss
> +.Select-control {
@colejoh apart from this, everything look good i think

2017-07-28 05:51 UTC, nickysemenza approved these changes

2017-07-28 05:52 UTC, nickysemenza commented
Merging this in, it'd be good to clean up the styling of the Select component like so: https://github.com/BoilerMake/frontend/pull/24#discussion_r129917833

Otherwise, great first PR 😄

2017-07-28 05:53 UTC, merged